# Generated by Django 5.1 on 2024-09-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_realisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realisation',
            name='after_image',
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='before_image',
        ),
        migrations.AddField(
            model_name='realisation',
            name='apres',
            field=models.ImageField(default='images/default.jpg', upload_to='images/apres/'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='avant',
            field=models.ImageField(default='images/apres/default.jpg', upload_to='images/avant/'),
            preserve_default=False,
        ),
    ]
