# Generated by Django 5.1 on 2024-09-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_utilisateur', models.CharField(choices=[('societe', 'Société'), ('particulier', 'Particulier')], max_length=20, verbose_name="Type d'utilisateur")),
                ('nom_ou_raison_sociale', models.CharField(max_length=255, verbose_name='Nom ou raison sociale')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('service_souhaite', models.CharField(max_length=255, verbose_name='Service souhaité')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Demande de devis',
                'verbose_name_plural': 'Demandes de devis',
                'ordering': ['nom_ou_raison_sociale'],
            },
        ),
    ]
