# Generated by Django 5.1 on 2024-09-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_devis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={},
        ),
        migrations.RemoveField(
            model_name='devis',
            name='nom_ou_raison_sociale',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='service_souhaite',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='type_utilisateur',
        ),
        migrations.AddField(
            model_name='devis',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='service',
            field=models.CharField(default='Nettoyage Ecologique & Sans Eau des Véhicules', max_length=255),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_client',
            field=models.CharField(choices=[('societe', 'Société'), ('particulier', 'Particulier')], default='societe', max_length=20),
        ),
        migrations.AlterField(
            model_name='devis',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='devis',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='devis',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
