# Generated by Django 5.1 on 2024-10-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_devis_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='fullname',
            field=models.CharField(default='John doe', max_length=255),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='61377398', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='Lavage', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default='exemple@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(default='Message'),
        ),
    ]
